### ISSUE TITLE
Since the first person light fix, lights now sometimes disappear entirely

### ISSUE THREAD

**Issue by PuffySandvich** [FredyH/Perpheads-Issues#909] opened 2019-07-06 19:09 UTC
https://i.imgur.com/kr9Xw1j.jpg

This also happens with police cars, and it tends to be all at once. this is very annoying when the lights are being used in a shootout to increase visibility, and also makes RC lights less effective

**Comment by ModoSN** [comment] 2019-07-10 19:48
explain the issue?

**Comment by PuffySandvich** [comment] 2019-07-11 19:42
> explain the issue?

click the image, you'll see exactly what the issue is. The lights aren't there, despite being on.

**Comment by TinySimon** [comment] 2019-07-15 15:10
Closing due to lack of information on what the issue is, or how to reproduce it

**Closed by TinySimon** 2019-07-15 15:10 UTC
Labels: can't reproduce
