### ISSUE TITLE
Game Breaking Lua Errors As TFU

### ISSUE THREAD

**Issue by R-Flexx** [FredyH/Perpheads-Issues#724] opened 2018-09-25 10:26 UTC
**Lua Errors as TFU at random times.**

**Cause :** Unknown , can happen at random times. It once happened as soon as another tfu officer took a taser out and shot it i think.

**Issues**
-Unable to look at the police computer database.
-PlayerModels not showing
-Script Errors

Sadly i didnt take a screenshot of the Original Script Error which caused the chained reaction

https://steamcommunity.com/sharedfiles/filedetails/?id=1522413770
https://steamcommunity.com/sharedfiles/filedetails/?id=1522413848
https://steamcommunity.com/sharedfiles/filedetails/?id=1522413896

**Comment by TinySimon** [comment] 2018-09-25 12:02
Duplicate of #682

**Closed by TinySimon** 2018-09-25 12:02 UTC
Labels: duplicate
