### ISSUE TITLE
inventory goes invisible, so do players and can't access police computer etc

### ISSUE THREAD

**Issue by Ardomaxi** [FredyH/Perpheads-Issues#698] opened 2018-09-01 19:49 UTC
i get this error 
[ERROR] gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:37: Tried to use a NULL entity!
  1. SetMoveType - [C]:-1
   2. Reattach - gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:37
    3. func - gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:54
     4. unknown - lua/includes/extensions/net.lua:32

CBaseEntityList::AddNonNetworkableEntity: no free slots!

[ERROR] gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:37: Tried to use a NULL entity!
  1. SetMoveType - [C]:-1
   2. Reattach - gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:37
    3. unknown - gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:65

Timer Failed! [Simple][@gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua (line 63)]
CBaseEntityList::AddNonNetworkableEntity: no free slots!

(its the same error repeated)

**Comment by Ardomaxi** [comment] 2018-09-01 19:50
this happens after a while and it gets very annoying i want to get rid of it permanently, reconnecting fixes it

**Comment by JaniceMcG** [comment] 2018-09-01 22:34
https://github.com/FredyH/Perpheads-Issues/issues/682

**Comment by TinySimon** [comment] 2018-09-03 15:11
Duplicate of #682

**Closed by TinySimon** 2018-09-03 15:11 UTC
Labels: duplicate
