### ISSUE TITLE
Light gear but Had heavy gear guns

### ISSUE THREAD

**Issue by SC3-Gazzy-Gaming** [FredyH/Perpheads-Issues#906] opened 2019-07-05 19:06 UTC
So I was gearing down from Heavy Gear and had a G36C, Then when I changed from Heavy to Light it kept the G36C. 
Also, sometimes armoury doesn't give armour aswell. 

Aquaa seemed very upset that I mentioned it in OOC And said I would be punished )when I alerted them about the bug) If I didn't get rid of it. >:(

**Comment by LoganFinch** [comment] 2019-07-06 14:00
#889 dupe

**Comment by TinySimon** [comment] 2019-07-07 13:29
Duplicate of #889

**Closed by TinySimon** 2019-07-07 13:29 UTC
