### ISSUE TITLE
Death/Spawn Logs show what weapon was used to kill someone but not Kill logs

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#890] opened 2019-06-28 15:58 UTC
pls fix

**Comment by LaCreepis** [comment] 2019-06-28 15:59
example https://i.imgur.com/8beJk3A.png

**Comment by TinySimon** [comment] 2019-06-30 13:17
This is technically a duplicate of #630 as the root cause is the same.

**Closed by TinySimon** 2019-06-30 13:17 UTC
