### ISSUE TITLE
Instant respawning

### ISSUE THREAD

**Issue by Jetfire242** [FredyH/Perpheads-Issues#768] opened 2018-11-15 19:25 UTC
While i was on duty as a officer on 15th november 2018, i was shot and killed at the slums by an assault rifle however i somehow skipped the 5 mins respawn screen (unconsius/ dead state) as i died. I was being bandaged by a fellow officer and i was also crippled as i was returning fire with my m9 berreta, the only form of evidance there is, is the respawn and death times being the same, this is as much as i can say at the time of creating this report.

evidance: https://prnt.sc/liuc6f

**Comment by TinySimon** [comment] 2018-12-09 00:14
Possibly caused by a entity becoming invalid in the same frame. In the example it isn't the killer entity but could be the inflicter entity, if different, or any of the players it tries to send a log to. Solution will either be adding more validity checks or moving the respawn timer definer further up the sequence.

**Comment by TinySimon** [comment] 2019-03-19 21:46
Closing due to no recent reports and no replication method

**Closed by TinySimon** 2019-03-19 21:46 UTC
Labels: can't reproduce
