### ISSUE TITLE
Respawning instantly on death

### ISSUE THREAD

**Issue by XxWhiteWolfxX** [FredyH/Perpheads-Issues#852] opened 2019-04-25 11:51 UTC
Hi,

Recently, I have come across this issue twice - when being shot (usually in the head) I have respawned instantly, I am unsure of anything relating to this and unsure which weapons were used specifically, however, said issue has occured to other people aswell.

The only possibly way of recreation could be killing someone and shooting them in the head (finishing them) before they hit the ground? As this appears to have happened or at least I believe to have happened previously to me.

I hope this does help.

**Comment by Sorleee** [comment] 2019-05-11 19:18
Has happened to me at least twice as well since I've been back.

**Comment by TinySimon** [comment] 2019-06-05 19:57
Duplicate of #850

**Closed by TinySimon** 2019-06-05 19:57 UTC
