### ISSUE TITLE
Guns at firing range bugged/glitched

### ISSUE THREAD

**Issue by crixxzeh** [FredyH/Perpheads-Issues#932] opened 2019-07-23 16:30 UTC
when you shoot your gun at firing range the firing rate is alot faster than normal and only the first bullet registers.

see below - https://youtu.be/uGjWWpCN1M4

**Comment by TinySimon** [comment] 2019-07-23 17:02
I can't reproduce this on my development server. Do you have a longer video or steps to reproduce it?

**Comment by Exnem** [comment] 2019-07-24 11:45
I believe this might have to do with changing fire modes too quickly.

**Comment by crixxzeh** [comment] 2019-07-24 21:04
Its completely random and might have something to do with 4;3 resolutions.
I was trying 1024x768 and 1280x960 with 90 fov, no idea if that would effect it but it seems random.

**Comment by LaCreepis** [comment] 2019-07-25 15:26
This very much looks like burst fire, but since that doesn't exist on a AK-101 did you shoot one before hand?

**Comment by SamuelSheppard** [comment] 2020-04-09 12:27
Dupe of #953

**Closed by SamuelSheppard** 2020-04-09 12:27 UTC
Labels: can't reproduce
